# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180815_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
