# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-10 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u65b0\u95fb\u7c7b\u578b')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u7c7b\u578b',
                'verbose_name_plural': '\u65b0\u95fb\u7c7b\u578b',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewType', verbose_name='\u65b0\u95fb\u7c7b\u578b'),
        ),
    ]
