# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181210_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, verbose_name='\u6bcf\u65e5\u4e00\u53e5')),
            ],
            options={
                'verbose_name': '\u6bcf\u65e5\u4e00\u53e5',
                'verbose_name_plural': '\u6bcf\u65e5\u4e00\u53e5',
            },
        ),
    ]
