# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('image', models.ImageField(blank=True, null=True, upload_to='impurity/%Y%m', verbose_name='\u8d44\u6e90\u63d2\u56fe')),
                ('is_free', models.BooleanField(default=True, verbose_name='\u662f\u5426\u514d\u8d39')),
            ],
            options={
                'verbose_name': '\u5206\u4eab\u8d44\u6e90',
                'verbose_name_plural': '\u5206\u4eab\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5206\u4eab\u7c7b\u578b')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u7c7b\u578b',
                'verbose_name_plural': '\u535a\u5ba2\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impurity.ShareType', verbose_name='\u5206\u4eab\u7c7b\u578b'),
        ),
    ]
