# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0002_auto_20190107_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='view_nums',
            field=models.IntegerField(default=20, verbose_name='\u67e5\u770b\u6b21\u6570'),
        ),
    ]
