# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u535a\u5ba2\u7c7b\u578b')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u7c7b\u578b',
                'verbose_name_plural': '\u535a\u5ba2\u7c7b\u578b',
            },
        ),
    ]
