# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180910_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='brief',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u7b80\u4ecb'),
        ),
    ]
